---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: "latest"


inputs:
  - name: git-repo
  - name: version

outputs:
  - name: artifact-dir

run:
  path: git-repo/ci/tasks/build-artifact.sh

params:
  base_name: