platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: service-repo
  - name: build-output

run:
  path: sh
  args: ["service-repo/ci/tasks/deploy.sh"]
