---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: "latest"


inputs:
  - name: release-candidate
  - name: version

outputs:
  - name: artifact-dir
  - name: expanded-artifact-dir

run:
  path: sh
  args: ["release-candidate/ci/tasks/extract-artifact.sh"]

params:
  base_name: