resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-test-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_TEST_ORG}}
    space: {{CF_TEST_SPACE}}
    skip_cert_check: ((skip-cert))

- name: deploy-uat-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_UAT_ORG}}
    space: {{CF_UAT_SPACE}}
    skip_cert_check: ((skip-cert))

- name: version
  type: semver
  source:
    driver: git
    uri: {{GIT_REPO}}
    branch: version
    file: version
    private_key: {{GIT_PRIVATE_KEY}}
    initial_version: 1.0.0

- name: release-candidate
  type: github-release
  source:
    owner: {{GIT_USER}}
    repository: {{GIT_RELEASE_REPO}}
    access_token: {{GIT_ACCESS_TOKEN}}

jobs:

  - name: build-artifact
    serial_groups: [version]
    serial: true
    plan:
    - get: git-repo
    #   passed: [unit-tests]
      trigger: true
    - get: version
      params: { pre: rc }
    - task: build-artifact
      file: git-repo/ci/tasks/build-artifact.yml
      timeout: 5m
      params:
        base_name: dotnet-demo
    - put: release-candidate
      params:
        name: git-repo/ci/name
        tag: version/number
        body: git-repo/ci/release-body
        globs:
          - artifact-dir/dotnet-demo*.gz
    - put: git-repo
      params:
        repository: git-repo
        tag: version/number
    - put: version
      params: {file: version/number}
    - put: deploy-test-app
      params:
        manifest: expanded-artifact-dir/manifest.yml
        current_app_name: dotnet-demo-test
        path: expanded-artifact-dir

  - name: uat-testing
    serial_groups: [version]
    plan:
    - aggregate:
      - get: version
        passed: [build-artifact]
      - get: release-candidate
        passed: [build-artifact]
      - get: git-repo
        passed: [build-artifact]
    - task: extract-artifact
      file: git-repo/ci/tasks/extract-artifact.yml
      timeout: 5m
      params:
        base_name: dotnet-demo
    - put: deploy-uat-app
      params:
        manifest: expanded-artifact-dir/manifest.yml
        current_app_name: dotnet-demo-uat
        path: expanded-artifact-dir
    #   params:
    #     manifest: git-repo/manifest-test.yml
    #     current_app_name: dotnet-demo-test
    #     path: release-candidate/dotnet-demo*.gz